prog:enemy.o main.o 
	gcc enemy.o main.o -o prog -lSDL -lSDL_image -lSDL_mixer -g
main.o:main.c
	gcc -c main.c -lSDL -lSDL_image -lSDL_mixer -g
enemy.o:enemy.c
	gcc -c enemy.c -lSDL -lSDL_image -lSDL_mixer -g
