prog:partage.o main.o 
	gcc partage.o main.o -o prog -lSDL -lSDL_image -lSDL_mixer -g
main.o:main.c
	gcc -c main.c -lSDL -lSDL_image -lSDL_mixer -g
partage.o:partage.c
	gcc -c partage.c -lSDL -lSDL_image -lSDL_mixer -g
